name: "Jan-Willem van de Meent @ robots.ox.ac.uk"
url: http://www.robots.ox.ac.uk
baseurl: http://www.robots.ox.ac.uk/~jwvdm
permalink: /:year/:month/:day/:title
timezone: Europe/London

navigation:
- text: About
  url: /index.html
- text: Anglican
  url: http://www.robots.ox.ac.uk/~fwood/anglican/
- text: Publications
  url: /publications/index.html

scholar:
  style: apa
  repository: assets/pdf
  bibliography_template: bibliography
